Don't attempt to recover failed unit tests
Currently with testify/assert, if a test fails then the test
attempts to recover and the remainder of the test then continues
to run, which just causes a mess (see the log below).

Modify the tests to use testify/require such that if a test
fails at any point, that test immediately bails with a fail
result.

An example log before this commit:

```
=== CONT  TestSuccessfullCommand
    machine_test.go:21:
        	Error Trace:	/__w/fakemachine/fakemachine/machine_test.go:21
        	            				/__w/fakemachine/fakemachine/machine_test.go:29
        	Error:      	Expected nil, but got: &errors.errorString{s:"uml backend not supported: user-mode-linux not installed"}
        	Test:       	TestSuccessfullCommand
--- FAIL: TestSuccessfullCommand (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x6f7042]

goroutine 28 [running]:
testing.tRunner.func1.2({0x731a80, 0x9fae90})
	/usr/lib/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/usr/lib/go/src/testing/testing.go:1399 +0x39f
panic({0x731a80, 0x9fae90})
	/usr/lib/go/src/runtime/panic.go:884 +0x212
github.com/go-debos/fakemachine.(*Machine).SetNumCPUs(...)
	/__w/fakemachine/fakemachine/machine.go:435
github.com/go-debos/fakemachine.CreateMachine(0xc000084d00?)
	/__w/fakemachine/fakemachine/machine_test.go:22 +0x62
github.com/go-debos/fakemachine.TestSuccessfullCommand(0xc000084d00)
	/__w/fakemachine/fakemachine/machine_test.go:29 +0x2f
testing.tRunner(0xc000084d00, 0x7b4d20)
	/usr/lib/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1493 +0x35f
FAIL	github.com/go-debos/fakemachine	0.023s
```

An example failing log after this commit:
```
=== CONT  TestSuccessfullCommand
    machine_test.go:22:
        	Error Trace:	/mnt/machine_test.go:22
        	            				/mnt/machine_test.go:30
        	Error:      	Expected nil, but got: &errors.errorString{s:"uml backend not supported: user-mode-linux not installed"}
        	Test:       	TestSuccessfullCommand
--- FAIL: TestSuccessfullCommand (0.00s)
```

Signed-off-by: Christopher Obbard <chris.obbard@collabora.com>